/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'event-types': EventType;
    events: Event;
    careers: Career;
    projects: Project;
    sponsors: Sponsor;
    'community-links': CommunityLink;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    'community-links': CommunityLinksSelect<false> | CommunityLinksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'general-settings': GeneralSetting;
    'site-settings': SiteSetting;
    'events-page-settings': EventsPageSetting;
    'careers-page-settings': CareersPageSetting;
    'projects-page-settings': ProjectsPageSetting;
  };
  globalsSelect: {
    'general-settings': GeneralSettingsSelect<false> | GeneralSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'events-page-settings': EventsPageSettingsSelect<false> | EventsPageSettingsSelect<true>;
    'careers-page-settings': CareersPageSettingsSelect<false> | CareersPageSettingsSelect<true>;
    'projects-page-settings': ProjectsPageSettingsSelect<false> | ProjectsPageSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: number;
  /**
   * Örn: cowork, workshop, talk, hackathon
   */
  slug: string;
  /**
   * Görünen isim (Örn: Cowork & Sohbet)
   */
  label: string;
  /**
   * Emoji veya simge (Örn: ☕, 🛠️, 🎤)
   */
  icon: string;
  /**
   * Modern HUD tema rengi (HEX)
   */
  colorModern: string;
  /**
   * Pixel Retro tema rengi (HEX)
   */
  colorPixel: string;
  isDefault?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Etkinlik türü seçin
   */
  type: number | EventType;
  status: 'upcoming' | 'completed' | 'cancelled';
  dateStart: string;
  dateEnd?: string | null;
  /**
   * Mekan adı (Örn: Coff The Story / Treehouse Cafe)
   */
  location?: string | null;
  /**
   * Google Maps bağlantısı
   */
  mapUrl?: string | null;
  capacity?: number | null;
  attendees?: number | null;
  /**
   * Etkinlik kapak görseli (Sürükle-bırak)
   */
  coverImage?: (number | null) | Media;
  /**
   * Harici görsel linki (Opsiyonel alternatif)
   */
  imageUrl?: string | null;
  /**
   * Etkinlik / Topluluk WhatsApp grup linki
   */
  whatsappLink?: string | null;
  /**
   * Etiketler (Örn: #WebDev, #AIAgents)
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Etkinlik detayları ve açıklaması
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  /**
   * İlan başlığı (Örn: Junior Frontend Developer)
   */
  title: string;
  /**
   * Şirket veya topluluk adı
   */
  company?: string | null;
  type: 'job' | 'internship' | 'freelance' | 'mentorship';
  workMode?: ('remote' | 'hybrid' | 'onsite') | null;
  schedule?: ('fulltime' | 'parttime' | 'project') | null;
  /**
   * Kullanılan teknolojiler (Örn: React, Node.js, TypeScript)
   */
  technologies?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * İlan detayları ve aranan nitelikler
   */
  description?: string | null;
  /**
   * Başvuru linki veya e-posta
   */
  applyUrl?: string | null;
  /**
   * İletişim kişisi veya platformu
   */
  contact?: string | null;
  /**
   * İlanı paylaşan kişi / kurum
   */
  postedBy?: string | null;
  /**
   * İlan yayında mı?
   */
  isActive?: boolean | null;
  /**
   * İlan bitiş tarihi
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Proje adı
   */
  name: string;
  /**
   * Proje açıklaması ve vizyonu
   */
  description?: string | null;
  type: 'showcase' | 'seeking_team' | 'opensource';
  /**
   * Projede kullanılan teknolojiler
   */
  technologies?:
    | {
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Proje sahibi / Takım lideri
   */
  owner?: string | null;
  teamSize?: number | null;
  teamMax?: number | null;
  /**
   * Aranan roller (Örn: UI Tasarımcı, Frontend Dev)
   */
  rolesNeeded?:
    | {
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * GitHub repo bağlantısı
   */
  githubUrl?: string | null;
  /**
   * Canlı demo bağlantısı
   */
  demoUrl?: string | null;
  /**
   * Proje kapak görseli
   */
  coverImage?: (number | null) | Media;
  /**
   * Harici görsel linki (Opsiyonel)
   */
  imageUrl?: string | null;
  /**
   * Topluluk beğeni sayısı
   */
  likes?: number | null;
  /**
   * Proje yayında mı?
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  /**
   * Sponsor / Destekçi adı
   */
  name: string;
  tier?: ('gold' | 'silver' | 'bronze' | 'community') | null;
  /**
   * Sponsor logo görseli
   */
  logo?: (number | null) | Media;
  /**
   * Harici logo linki (Opsiyonel)
   */
  logoUrl?: string | null;
  /**
   * Sponsor web sitesi bağlantısı
   */
  websiteUrl: string;
  /**
   * Sıralama önceliği (Küçük sayılar önce çıkar)
   */
  sortOrder?: number | null;
  /**
   * Sponsor yayında mı?
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-links".
 */
export interface CommunityLink {
  id: number;
  /**
   * Benzersiz anahtar (Örn: whatsapp_coworking, whatsapp_projects, whatsapp_careers)
   */
  key: string;
  /**
   * Görünen etiket (Örn: WhatsApp Coworking Grubu)
   */
  label: string;
  /**
   * Bağlantı adresi (URL)
   */
  url: string;
  /**
   * Kısa açıklama
   */
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'event-types';
        value: number | EventType;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null)
    | ({
        relationTo: 'community-links';
        value: number | CommunityLink;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  icon?: T;
  colorModern?: T;
  colorPixel?: T;
  isDefault?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  status?: T;
  dateStart?: T;
  dateEnd?: T;
  location?: T;
  mapUrl?: T;
  capacity?: T;
  attendees?: T;
  coverImage?: T;
  imageUrl?: T;
  whatsappLink?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  type?: T;
  workMode?: T;
  schedule?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  description?: T;
  applyUrl?: T;
  contact?: T;
  postedBy?: T;
  isActive?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  technologies?:
    | T
    | {
        name?: T;
        id?: T;
      };
  owner?: T;
  teamSize?: T;
  teamMax?: T;
  rolesNeeded?:
    | T
    | {
        role?: T;
        id?: T;
      };
  githubUrl?: T;
  demoUrl?: T;
  coverImage?: T;
  imageUrl?: T;
  likes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  logo?: T;
  logoUrl?: T;
  websiteUrl?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-links_select".
 */
export interface CommunityLinksSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  url?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings".
 */
export interface GeneralSetting {
  id: number;
  meta: {
    siteTitle: string;
    defaultDescription: string;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  header?: {
    announcementActive?: boolean | null;
    announcementText?: string | null;
    announcementUrl?: string | null;
  };
  footer?: {
    tagline?: string | null;
    locationCoordinates?: string | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hero?: {
    cityCoordinates?: string | null;
    title?: string | null;
    titleHighlight?: string | null;
    subtitle?: string | null;
    description?: string | null;
  };
  /**
   * Ana sayfadaki sayaç kartları (Örn: 150+ Topluluk Üyesi)
   */
  stats?:
    | {
        target: number;
        prefix?: string | null;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        icon: string;
        title: string;
        description: string;
        tags?: string | null;
        id?: string | null;
      }[]
    | null;
  personas?:
    | {
        icon: string;
        title: string;
        description: string;
        tags?: string | null;
        id?: string | null;
      }[]
    | null;
  flowSteps?:
    | {
        num: string;
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  careerResources?:
    | {
        icon: string;
        title: string;
        desc: string;
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page-settings".
 */
export interface EventsPageSetting {
  id: number;
  hero: {
    tag: string;
    title: string;
    highlightText: string;
    description: string;
  };
  whatsappCta?: {
    buttonText?: string | null;
    overrideUrl?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page-settings".
 */
export interface CareersPageSetting {
  id: number;
  hero: {
    tag: string;
    title: string;
    highlightText: string;
    description: string;
  };
  whatsappCta?: {
    buttonText?: string | null;
    overrideUrl?: string | null;
  };
  careerResources?:
    | {
        icon: string;
        title: string;
        desc: string;
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page-settings".
 */
export interface ProjectsPageSetting {
  id: number;
  hero: {
    tag: string;
    title: string;
    highlightText: string;
    description: string;
  };
  whatsappCta?: {
    buttonText?: string | null;
    overrideUrl?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "general-settings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        siteTitle?: T;
        defaultDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  header?:
    | T
    | {
        announcementActive?: T;
        announcementText?: T;
        announcementUrl?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        locationCoordinates?: T;
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        cityCoordinates?: T;
        title?: T;
        titleHighlight?: T;
        subtitle?: T;
        description?: T;
      };
  stats?:
    | T
    | {
        target?: T;
        prefix?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        tags?: T;
        id?: T;
      };
  personas?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        tags?: T;
        id?: T;
      };
  flowSteps?:
    | T
    | {
        num?: T;
        title?: T;
        desc?: T;
        id?: T;
      };
  careerResources?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page-settings_select".
 */
export interface EventsPageSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        tag?: T;
        title?: T;
        highlightText?: T;
        description?: T;
      };
  whatsappCta?:
    | T
    | {
        buttonText?: T;
        overrideUrl?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page-settings_select".
 */
export interface CareersPageSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        tag?: T;
        title?: T;
        highlightText?: T;
        description?: T;
      };
  whatsappCta?:
    | T
    | {
        buttonText?: T;
        overrideUrl?: T;
      };
  careerResources?:
    | T
    | {
        icon?: T;
        title?: T;
        desc?: T;
        tag?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page-settings_select".
 */
export interface ProjectsPageSettingsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        tag?: T;
        title?: T;
        highlightText?: T;
        description?: T;
      };
  whatsappCta?:
    | T
    | {
        buttonText?: T;
        overrideUrl?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}